
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DO IDENTIFIER LBRACE LPAREN RBRACE RPAREN SEMICOLON WHILEdo_while_loop : DO LBRACE statements RBRACE WHILE LPAREN condition RPAREN SEMICOLONcondition : condition IDENTIFIER\n                 | IDENTIFIERstatements : statement statements\n                  | statementstatement : do_while_loop\n                 | condition SEMICOLON'
    
_lr_action_items = {'DO':([0,3,6,7,10,17,],[2,2,2,-6,-7,-1,]),'$end':([1,17,],[0,-1,]),'LBRACE':([2,],[3,]),'IDENTIFIER':([3,5,6,7,8,10,11,14,15,17,],[8,11,8,-6,-3,-7,-2,8,11,-1,]),'RBRACE':([4,6,7,10,12,17,],[9,-5,-6,-7,-4,-1,]),'SEMICOLON':([5,8,11,16,],[10,-3,-2,17,]),'RPAREN':([8,11,15,],[-3,-2,16,]),'WHILE':([9,],[13,]),'LPAREN':([13,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'do_while_loop':([0,3,6,],[1,7,7,]),'statements':([3,6,],[4,12,]),'condition':([3,6,14,],[5,5,15,]),'statement':([3,6,],[6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> do_while_loop","S'",1,None,None,None),
  ('do_while_loop -> DO LBRACE statements RBRACE WHILE LPAREN condition RPAREN SEMICOLON','do_while_loop',9,'p_do_while_loop','5-dowhile.py',53),
  ('condition -> condition IDENTIFIER','condition',2,'p_condition','5-dowhile.py',57),
  ('condition -> IDENTIFIER','condition',1,'p_condition','5-dowhile.py',58),
  ('statements -> statement statements','statements',2,'p_statements','5-dowhile.py',65),
  ('statements -> statement','statements',1,'p_statements','5-dowhile.py',66),
  ('statement -> do_while_loop','statement',1,'p_statement','5-dowhile.py',73),
  ('statement -> condition SEMICOLON','statement',2,'p_statement','5-dowhile.py',74),
]
